#!/bin/bash

SSHVARS="SSH_CLIENT SSH_TTY SSH_AUTH_SOCK SSH_CONNECTION DISPLAY"

mkdir -p $HOME/.fixssh

for x in ${SSHVARS} ; do
  y=`env | grep $x`
  if [ ! -z "$y" ]
  then
    (eval echo $x=\$$x) | sed  's/=/="/
                                s/$/"/
                                s/^/export /'
  fi
done 1>$HOME/.fixssh/fixssh-$HOSTNAME
